on:
  push:
    branches: [main]

jobs:
  publish-image:
    name: Publish Docker image
    runs-on: docker
    permissions:
      packages: write
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Publish image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        repo: codeberg.org/${CI_REPO_OWNER}/dasBlog
        registry: codeberg.org
        tags: latest
        username: ${CI_REPO_OWNER}
        password: ${{secrets.DOCKER_TOKEN}}
